# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 49ef8fb3001a0d3d07fb85c0c3ed61e65306c4352f55ee0eb45af076247b81e2138287c02c2e4fdae8935bcde07316b7a755dbede50b3ed90751497b9a63b720

test:
  secret_key_base: 80fadbdb9574473524887c04c4c175ae7a0e867aa8438fee1b143a53abf0b65596e4641d9937ff9ce7f8ee06fda8bc0aeb1b7f784c357a531f8e0e5d2aa3b35f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
